#!/usr/bin/env python3
"""Generate a C++ header of LED ids from an SVG whose LEDs are <rect id="led123"> elements.

Usage:
  python3 gen_led_rows.py fin-ltm.svg            # group by y (rows)
  python3 gen_led_rows.py hki-ltm.svg --axis x   # group by x (columns)

- Ancestor + own transforms (rotate/scale/translate/matrix...) are composed, so
  positions are true document coordinates.
- --axis y (default): rows. LEDs sorted by y (top -> bottom, SVG y grows downward);
  a row starts at its first LED and includes every LED within one LED height in y of
  that first LED. Within a row, LEDs are sorted left -> right by x.
- --axis x: columns. LEDs sorted by x (left -> right); a column starts at its first
  LED and includes every LED within one LED width in x of that first LED. Within a
  column, LEDs are sorted top -> bottom by y.
"""
import argparse
import re, math, sys
import xml.etree.ElementTree as ET
import numpy as np

SVG = '{http://www.w3.org/2000/svg}'

def parse_transform(s):
    m = np.identity(3)
    for name, args in re.findall(r'(\w+)\s*\(([^)]*)\)', s or ''):
        a = [float(v) for v in re.split(r'[\s,]+', args.strip()) if v]
        t = np.identity(3)
        if name == 'matrix':
            t = np.array([[a[0], a[2], a[4]], [a[1], a[3], a[5]], [0, 0, 1]])
        elif name == 'translate':
            t[0, 2], t[1, 2] = a[0], (a[1] if len(a) > 1 else 0)
        elif name == 'scale':
            t[0, 0], t[1, 1] = a[0], (a[1] if len(a) > 1 else a[0])
        elif name == 'rotate':
            r = math.radians(a[0]); c, s_ = math.cos(r), math.sin(r)
            t = np.array([[c, -s_, 0], [s_, c, 0], [0, 0, 1]])
            if len(a) == 3:
                t = parse_transform(f'translate({a[1]},{a[2]})') @ t @ parse_transform(f'translate({-a[1]},{-a[2]})')
        elif name == 'skewX':
            t[0, 1] = math.tan(math.radians(a[0]))
        elif name == 'skewY':
            t[1, 0] = math.tan(math.radians(a[0]))
        m = m @ t
    return m

def collect(el, ctm, out):
    ctm = ctm @ parse_transform(el.get('transform'))
    if el.tag == SVG + 'rect' and re.fullmatch(r'led\d+', el.get('id', '')):
        x, y = float(el.get('x', 0)), float(el.get('y', 0))
        w, h = float(el.get('width')), float(el.get('height'))
        p = ctm @ np.array([[x, y, 1], [x + w, y, 1], [x + w, y + h, 1], [x, y + h, 1]]).T
        # LED "height" = length of the local-y edge in document units
        h_edge = math.hypot(*(p[:2, 3] - p[:2, 0]))   # local-y edge
        w_edge = math.hypot(*(p[:2, 1] - p[:2, 0]))   # local-x edge
        out.append(dict(id=int(el.get('id')[3:]), x=p[0].mean(), y=p[1].mean(), h=h_edge, w=w_edge))
    for ch in el:
        collect(ch, ctm, out)

def main(path, axis):
    leds = []
    collect(ET.parse(path).getroot(), np.identity(3), leds)
    if not leds:
        sys.exit('no led rects found')

    # primary = axis we group along; secondary = order inside a group
    prim, sec, size_key = ('y', 'x', 'h') if axis == 'y' else ('x', 'y', 'w')
    noun, Noun, NOUN = ('row', 'Row', 'ROW')
    order = ('top -> bottom by y; left -> right by x within a row' if axis == 'y'
             else 'left -> right by x; top -> bottom by y within a column')
    within = 'left -> right' if axis == 'y' else 'top -> bottom'
    unit = 'height' if axis == 'y' else 'width'

    tol = float(np.median([l[size_key] for l in leds]))
    leds.sort(key=lambda l: l[prim])
    groups = []
    for l in leds:
        if groups and l[prim] - groups[-1][0][prim] <= tol:
            groups[-1].append(l)
        else:
            groups.append([l])
    for g in groups:
        g.sort(key=lambda l: l[sec])

    o = []
    o.append('// Auto-generated by gen_led_rows.py from %s' % path.split('/')[-1])
    o.append('// %d LEDs in %d %ss (%s).' % (len(leds), len(groups), noun, order))
    o.append('// Grouping tolerance: %.3f (1 LED %s, SVG document units).' % (tol, unit))
    o.append('#pragma once')
    o.append('#include <stdint.h>')
    o.append('#include <stddef.h>')
    o.append('')
    o.append('struct Led%s {' % Noun)
    o.append('  const int* ids;   // LED ids in this %s, %s' % (noun, within))
    o.append('  uint8_t    count; // number of LEDs in this %s' % noun)
    o.append('};')
    o.append('')
    for i, g in enumerate(groups):
        o.append('// %s ~ %.2f' % (prim, np.mean([l[prim] for l in g])))
        o.append('static constexpr int LED_%s_%d[] = {%s};' % (NOUN, i, ', '.join(str(l['id']) for l in g)))
    o.append('')
    o.append('static constexpr Led%s LED_%sS[] = {' % (Noun, NOUN))
    for i, g in enumerate(groups):
        o.append('  {LED_%s_%d, %d},' % (NOUN, i, len(g)))
    o.append('};')
    o.append('')
    o.append('static constexpr size_t LED_%s_COUNT = sizeof(LED_%sS) / sizeof(LED_%sS[0]);' % (NOUN, NOUN, NOUN))
    # LED_TOTAL kept for the row header for backward compatibility; columns get their own name
    o.append('static constexpr size_t %s = %d;' % ('LED_TOTAL' if axis == 'y' else 'LED_COL_TOTAL', len(leds)))
    print('\n'.join(o))

if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('svg')
    ap.add_argument('--axis', choices=['x', 'y'], default='y',
                    help="y = group into rows (default), x = group into columns")
    a = ap.parse_args()
    main(a.svg, a.axis)
